### ISSUE TITLE
Negative Multiplicity in HTML

### ISSUE THREAD

**Issue by schlpbch** [VDVde/OJP#159]
Strangely, sometimes the multiplicity are negative in the HTML generated:

![NegativeMulticipliesInHTML](https://user-images.githubusercontent.com/18540761/119667747-db330f00-be36-11eb-86d2-ac0c4fe656a8.PNG)

**Comment by ue71603** [comment]
@schlpbch @jmaerki  @skinkie 
If necessary please update the issue if necessary:

From @sgrossberndt 
as I wrote yesterday

https://github.com/VDVde/OJP/pull/154#issuecomment-865030534

the pull request must be updated.

Codewise the pull request looks fine, but Stefan mentioned that Andreas Schlapbach found some rendering issues with tables. Andreas should add an issue at https://github.com/VDVde/OJP/issues - if the mentioned issue is not https://github.com/VDVde/OJP/issues/159.

**Comment by ue71603** [comment]
nothing left to do for the time being.

**Comment by sgrossberndt** [comment]
After having a look at the documentation tables at https://vdvde.github.io/OJP/generated/OJP.html#TripLegStructure once again I'd like to speak about this one again:
In my opinion the minus prefix is no longer necessary in the current layout. In the former layout it was necessary to distinguish between "normal" elements and choices. Since the current layout already makes this clear by a line "Then, the element contains one of the following elements:" above and also contains the "a","b","c",... in front of the elements:

**Comment by sgrossberndt** [comment]
Since we adhere to the SIRI layout of tables this should stay. But like https://github.com/VDVde/OJP/issues/172 when hovering it should be explained in the title text what this is about

**Comment by sgrossberndt** [comment]
Looks good. Will add a pull request.

**Comment by sgrossberndt** [comment]
As the change is within your own repository and not available as a branch in [OJP](https://github.com/VDVde/OJP) it seems I cannot create a pull request from it honoring your work, @jmaerki.

**Comment by sgrossberndt** [comment]
Merged in https://github.com/VDVde/OJP/pull/233
