### ISSUE TITLE
IndividualTransportMode = "public-transport" or "bus"

### ISSUE THREAD

**Issue by ue71603** [VDVde/OJP#164]
Hi everbody. 

The individual mode routing sometimes need to route also for a bus (e.g. when LinkProjection is activated).

When routing e.g. in OSM the rules for public transport is different. Or do you think that the LinkProjection for public transport should be used from another source than the IV routing graph?

Kind regards
Matthias

**Comment by skinkie** [comment]
@ue71603 OSM = OpenStreetMap or OSDM = Open Sales Distribution Model?

**Comment by ue71603** [comment]
In our OJP implementation we use currently OSM as the basis for the individual mode routing graph.

**Comment by skinkie** [comment]
Ok what do you mean with "LinkProjection is activated"? Do you mean a route between where the bus stops and the bus stop? Or the route over the road? In my perspective as a journey planner builder, there is a timetabled journey planner operating on time and a part that calculates times between non-public transport endpoints.

**Comment by ue71603** [comment]
Sorry, wrong wording I mean IncludeLegProjection=true in the parameters. Somewhere that information ist coming from. There might be sources that have them in the NeTEx. Currently we load it from OSM. 
![image](https://user-images.githubusercontent.com/24227470/122934860-2e35ae80-d370-11eb-97bb-c4a46c444fb9.png)

**Comment by pvgrumbkow** [comment]
In my point of view, the actual source of the LegProjection should be of no matter to the requestor. I don't see any relation to individual transport. In most cases, the leg projection of individual transport will have its source in the corresponding routing system. In most cases, the leg projection of public transport will have its source in the corresponding timetable data. Nethertheless, this is not necessary and I don't see any issue in the requestor not knowing the data source.
In our case, the leg projection of public transport busses will usually come from the timetable data. That is, because sometimes public transport busses don't take the shortes (or fastest) route between two consecutive stops.

**Comment by ue71603** [comment]
OK. so we close this issue.
