### ISSUE TITLE
Documentation malformed NumberOfResults / BaseTripPolicy

### ISSUE THREAD

**Issue by skinkie** [VDVde/OJP#165]
![image](https://user-images.githubusercontent.com/502394/123295112-b1443980-d515-11eb-9b40-f02f2f131c8e.png)

**Comment by jmaerki** [comment]
Thanks, should be fixed now.

**Comment by schlpbch** [comment]
![image](https://user-images.githubusercontent.com/18540761/123406306-0ed69580-d5ab-11eb-843e-2da0143d5871.png)

This suggests that `PointOfInterestRef` is of type `PointOfInterestRef` which would be infinite loop.

**Comment by jmaerki** [comment]
Yes, that's a consequence of the documentation rules where I remove the "Structure" Suffix. How would you expect this to be resolved? I can't just remove the "Ref" at the end because that would create another conflict between "PointOfInterestRef", "PointOfInterestRefStructure" and "PointOfInterest". Same for "TopographicPlace*". The only way out is to remove the rule that removes the "Structure" Suffix.

**Comment by sgrossberndt** [comment]
In order not to bloat the table we will keep the removal of the "Type" and "Structure" suffix. It is documented as well in the word file:

> In order to save space, data types have been truncated. So endings like “Structure” and “Type” are not written out. Instead of “InternationalTextStructure” the data type will be indicated as “InternationalText”.

**Comment by trurlurl** [comment]
Removed *documentation* label as the documentation-related work has been done.
