### ISSUE TITLE
Documentation: Improve layout for choices in sequences

### ISSUE THREAD

**Issue by sgrossberndt** [VDVde/OJP#188]
The rootlevel element `OJP` contains a sequence of two elements, where the first element is a choice:

https://github.com/VDVde/OJP/blob/changes_for_v1.1/OJP.xsd#L15
```
			<xs:sequence>
				<xs:choice>
					<xs:element ref="OJPRequest"/>
					<xs:element ref="OJPResponse"/>
				</xs:choice>
				<xs:element ref="Extensions" minOccurs="0"/>
			</xs:sequence>
```

which will currently be rendered like this:
![Screenshot 2022-04-25 at 10-18-06 OJP - Open API for distributed Journey Planning](https://user-images.githubusercontent.com/3786510/165048966-c658f4aa-87a7-4582-80f8-3907a1611b88.png)

This is not good because of the line "The element contains a sequence of the following elements:" and "Then, the element contains one of the following elements:" directly beneath it, which makes it hard to understand what is part of the sequence and what is part of the choice.

I don't have a good solution, but maybe the line "Then, the element contains one of the following elements:" should have a empty cell in front of it like the other elements of the sequence have it?

https://vdvde.github.io/OJP/generated/OJP.html#OJP

**Comment by ue71603** [comment]
Jeremias said, that this would kill everything he has done and he has not really the time to do it. The indentation would have been to costly. The current form is a compromise already. 

My suggestion would be not do add a cell, but to perhaps to ident the text and for inner structures always have a sort of endline

So in this case and not doing anything additional with the cells.

Sequence
   Choice
       a
       b
   End choice
   Extensions


Can you coordinate with Jeremias, what is feasible? and simple? @sgrossberndt

**Comment by ue71603** [comment]
- Thicker line in the table after the choice: We need to explain why this is a thick line.
- Using the the first column of "choice" with a <<choice>> in every cell of every line being part of the included element.+<-- prefered

To be discussed with Jeremias.

**Comment by ue71603** [comment]
If needed done for inner sequences. or using brackets.

**Comment by jmaerki** [comment]
Sorry, but I don't quite understand all proposals here and see problems with those I think I understand. Anyway, just look at "DatedJourneyStructure". Pressing that structure into the flattened table messes up a lot already when the current rules are applied. Those inlined groups... 🙈 If you start adding even more visual sugar, we end up with people then complaining that other things are not clear. The only place that properly explains the structure of the schema is the XSD itself. A developer will always work off the XSD as the normative and correct source of information because that's how he can automatically validate his application's output (or the input he has to consume). I see the tabular form only as a helper for less technical people happy with a slightly smaller information set. And I don't see a practical and economical way to map all the structure and information of the schema into that simplified table. I've seen other attempts in the wild and I've always reverted to checking the XSDs when it came to getting the details right. To me, this feels like trying to square the circle, but that's just my personal opinion.

**Comment by sgrossberndt** [comment]
We will have to live without that change for now then
