### ISSUE TITLE
Other Accessibility related issues, that I am not sure are covered yet.

### ISSUE THREAD

**Issue by ue71603** [VDVde/OJP#278]
•	The onlyGuaranteedInterachanges might be needed to add to TripFilter somewhere
•	Some of the explnations

**Comment by ue71603** [comment]
@trurlurl 
When I went through the older PR/issues i felt that some of the explanations and the onlyGauranteedInterchanges are not yet covered. Am I wrong or is there some work necessary?

**Comment by trurlurl** [comment]
onlyGuaranteedInterchanges - in my understanding this is now part of what the OptimisationMethod *extraReliable* wants to achieve (PR #271). There is an existing element *guaranteedConnection* I had mentioned that the OptimisationMethod should consider, but I guess the implementors will find that on their own.

Other explanations I remember are the documentation annotations for the OptimisationMethods, now in the proposed PR #273.

I don't remember anything else - @ue71603 or do you have some hint about something else that is or might be missing? Otherwise, my impression is that nothing more needs to be done.

**Comment by ue71603** [comment]
@trurlurl I guess, I did not check thoroughly enough. Then I close this issue. Thanks for the information.

**Comment by trurlurl** [comment]
Documentation ok or delegated to other open PRs.
