### ISSUE TITLE
Use generated HTML tables in Word document? 

### ISSUE THREAD

**Issue by trurlurl** [VDVde/OJP#315]
There is quite an easy way to convert the automatically generated HTML tables to tables in Word that look like being usable.

The steps are:
1. Read / import the HTML file into Word (via Insert - Text - Object ...)
2. Change text format for complete content to Cambria, 8 pt
3. For each table, apply template "normal"
See the attached document for a result of this. 

The tables could be copied to the appropriate sections in the specification document, I'd suggest to simply remove the rows stating "The element contains ...".

Points to consider and discuss:
A) Edit tables with enums to add annotations?
B) The links are "semi functional" - they jump to the approximate place in the table of contents, from where one could jump back to the wanted table. When exported as PDF, the links cease to work. 
C) In case of modifications in the code, either complete tables or only the modifications have to be transferred to the specification.
D) In case of typos we want to eliminate from the specification document, the code should be changed, requiring a pull request.
E) We'd have more explicit indirections and additional tables as compared with the current notation. Example:
Currently in Word: AddressRef / ->Address
Generated: ->AddressRef / ->AddressRef , plus table AddressRef / +AddressRef, plus table AddressRefStructure / AddressCode
(By the way: there seems to be a bug with the similar table TopographicPlaceRefStructure, a field is empty)
F) Other points ...?

[OJP Tables V01.docx](https://github.com/VDVde/OJP/files/10518826/OJP.Tables.V01.docx)

**Comment by sgrossberndt** [comment]
A) Yes, the generation of the documentation tables should be adapted to show the annotation of enums

B) I have no experience in getting automatically generated content into a Word document. The former state of the generation of the tables was to have asciidoc as an interim step in the generation and then create html from it. asciidoc would have allowed to [more easily generate a word document from it](https://rmoff.net/2020/04/16/converting-from-asciidoc-to-google-docs-and-ms-word/). Since the rewrite from #154 this is not the case anymore, the intermediate is an xml file, which is then rendered to HTML using `ojp-prep-to-html-with-toc.xsl`. Using another xsl file here to generate another file would allow you to adapt the html to be conformant to Word. Maybe @jmaerki maybe of help here?

C) Yes and that would be the wanted behaviour to be up to date, so there should in the best case be no or very few manual work necessary to get a generated state into the documentation

D) Yes and that would be the wanted behaviour to be up to date

E) The current pointer in the Word document is not accurate, because the needed structure here is an `AddressRefStructure`, not an `AddressStructure`
 Please create an issue for the TopographicPlaceRefStructure bug, explaining what is wrong, best to add a screenshot

**Comment by trurlurl** [comment]
B) I just found an easy solution to make the links work, even in a generated PDF. 
(Select structure name in section title, e.g., "ContactDetailsStructure"; goto tab "Insert" - Bookmark/Textmarke; add proper token name "ContactDetailsStructure") This has only to be done once for each section. 

Considering this and Stephan's answers, I have the impression that we could go with the generated tables. Enum annotations should be added by hand for the time being - or is the automatic generation of enum annotations (point A) to be expected in the near future?

**Comment by sgrossberndt** [comment]
Using the generated tables is a good choice in my opinion.

Regarding the automatic generation of enum annotations: Depends on whether you or @jmaerki have time to extend it 😬
Sorry, I cannot help here currently due to time constraints. :-(

**Comment by ue71603** [comment]
I think Jeremias has no time. He gave us another person. Perhaps we do the Enum manually. I will check.

**Comment by trurlurl** [comment]
Updated description of the steps:

**In an empty Word document:**

1. Read / import the HTML file into Word (via Insert - Text - Object - Text from file)
2. Change text format for the complete content to Cambria, 8 pt
3. Change paragraph settings for the complete content as follows:
![grafik](https://user-images.githubusercontent.com/82838870/234035982-3d77ef07-eb69-4bc8-b1c4-14e1261aa95e.png)


4. For each table, apply template "normal":
![grafik](https://user-images.githubusercontent.com/82838870/234036359-218df3e2-e629-4c08-aca0-dfdbe3ce5f7b.png)


**In the specification document:**

1. In the first column of the copied tables, remove any hyperlinks (they point to *groups* - for which there are no separate documentation tables)
2. For each new section added for a table, mark the name in the section title as a referencable / linkable token:
![grafik](https://user-images.githubusercontent.com/82838870/234036514-e21046c4-b7d3-44df-8a63-f0fbf9d0fd65.png)

**Comment by trurlurl** [comment]
Generated documentation tables have been copied to the specification document. For future versions, improved tables from the Xcore documentation tool will be available.
